version: '3.7'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    logging: 
      options: 
        max-size: 10m,
        max-file: "3"
    environment:
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_USER=imskanand
